/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import model.User;
/**
 *
 * @author Ricardo Ferreira
 */
public class Favorites extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Favorites.class.getName());
    private User user;
    private controller.FavoritesControl c;
    /**
     * Creates new form Favorites
     */
    public Favorites(User user) {
        initComponents();
        this.user = user;
        
        c = new controller.FavoritesControl(this);

        tbl_favorites.setDefaultEditor(Object.class, null);

        c.loadFavorites();
        
        tbl_favorites.setDefaultEditor(Object.class, null);
        tbl_favorites.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        btn_removeFavorite.setEnabled(false);

        tbl_favorites.getSelectionModel().addListSelectionListener(e -> {
            btn_removeFavorite.setEnabled(tbl_favorites.getSelectedRow() != -1);
        });
    }
    
    public User getUser() {
        return user;
    }

    public javax.swing.JTable getTbl_favorites() {
        return tbl_favorites;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_openFavorites = new javax.swing.JButton();
        btn_backHome = new javax.swing.JButton();
        btn_removeFavorite = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_favorites = new javax.swing.JTable();
        lbl_titleFavorites = new javax.swing.JLabel();
        lbl_titleLists = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_playlists = new javax.swing.JTable();
        btn_backHome1 = new javax.swing.JButton();
        btn_backHome2 = new javax.swing.JButton();
        btn_backHome3 = new javax.swing.JButton();
        btn_backHome4 = new javax.swing.JButton();
        txt_playlistName = new javax.swing.JTextField();

        btn_openFavorites.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_openFavorites.setText("Favoritos");
        btn_openFavorites.addActionListener(this::btn_openFavoritesActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_backHome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_backHome.setText("Voltar");
        btn_backHome.setToolTipText("");
        btn_backHome.addActionListener(this::btn_backHomeActionPerformed);

        btn_removeFavorite.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_removeFavorite.setText("Remover Favorito");
        btn_removeFavorite.addActionListener(this::btn_removeFavoriteActionPerformed);

        tbl_favorites.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Título", "Tipo", "Descrição"
            }
        ));
        jScrollPane1.setViewportView(tbl_favorites);

        lbl_titleFavorites.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        lbl_titleFavorites.setText("Meus Favoritos");

        lbl_titleLists.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        lbl_titleLists.setText("Minhas Listas");

        tbl_playlists.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Qtd. Vídeos"
            }
        ));
        jScrollPane2.setViewportView(tbl_playlists);

        btn_backHome1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_backHome1.setText("Nova Lista");
        btn_backHome1.setToolTipText("");
        btn_backHome1.addActionListener(this::btn_backHome1ActionPerformed);

        btn_backHome2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_backHome2.setText("Renomear");
        btn_backHome2.setToolTipText("");
        btn_backHome2.addActionListener(this::btn_backHome2ActionPerformed);

        btn_backHome3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_backHome3.setText("Excluir");
        btn_backHome3.setToolTipText("");
        btn_backHome3.addActionListener(this::btn_backHome3ActionPerformed);

        btn_backHome4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_backHome4.setText("Abrir");
        btn_backHome4.setToolTipText("");
        btn_backHome4.addActionListener(this::btn_backHome4ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_removeFavorite)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_backHome))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_backHome1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_backHome4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_backHome2)
                                .addGap(18, 18, 18)
                                .addComponent(btn_backHome3)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txt_playlistName, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_titleFavorites)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_titleLists)
                        .addGap(123, 123, 123))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_titleFavorites, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_titleLists, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_playlistName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_removeFavorite)
                            .addComponent(btn_backHome))
                        .addGap(57, 57, 57)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_backHome3)
                    .addComponent(btn_backHome1)
                    .addComponent(btn_backHome4)
                    .addComponent(btn_backHome2))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_openFavoritesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openFavoritesActionPerformed
        new view.Favorites(user).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_openFavoritesActionPerformed

    private void btn_backHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backHomeActionPerformed
        new view.Home(user).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backHomeActionPerformed

    private void btn_removeFavoriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeFavoriteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_removeFavoriteActionPerformed

    private void btn_backHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backHome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_backHome1ActionPerformed

    private void btn_backHome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backHome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_backHome2ActionPerformed

    private void btn_backHome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backHome3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_backHome3ActionPerformed

    private void btn_backHome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backHome4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_backHome4ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Favorites().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_backHome;
    private javax.swing.JButton btn_backHome1;
    private javax.swing.JButton btn_backHome2;
    private javax.swing.JButton btn_backHome3;
    private javax.swing.JButton btn_backHome4;
    private javax.swing.JButton btn_openFavorites;
    private javax.swing.JButton btn_removeFavorite;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_titleFavorites;
    private javax.swing.JLabel lbl_titleLists;
    private javax.swing.JTable tbl_favorites;
    private javax.swing.JTable tbl_playlists;
    private javax.swing.JTextField txt_playlistName;
    // End of variables declaration//GEN-END:variables
}
