/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JTable;
import model.User;

/**
 *
 * @author Ricardo Ferreira
 */
public class Home extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Home.class.getName());
    private User user;
    private controller.HomeControl c;
    
    /**
     * Creates new form Home
     */
    public Home(User user) {
        initComponents();
        this.user = user;
        c = new controller.HomeControl(this);
        
        //Blocks table editing manually;
        tbl_videos.setDefaultEditor(Object.class, null);
        tbl_videos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        
        tbl_videos.getColumnModel().getColumn(0).setMinWidth(0);
        tbl_videos.getColumnModel().getColumn(0).setMaxWidth(0);
        tbl_videos.getColumnModel().getColumn(0).setWidth(0);
        
        btn_favoriteVideo.setEnabled(false);

        tbl_videos.getSelectionModel().addListSelectionListener(e -> {
            boolean selected = tbl_videos.getSelectedRow() != -1;

            btn_likeVideo.setEnabled(selected);
            btn_dislikeVideo.setEnabled(selected);
            btn_favoriteVideo.setEnabled(selected);
        });
        
        btn_likeVideo.setEnabled(false);
        btn_dislikeVideo.setEnabled(false);

        tbl_videos.getSelectionModel().addListSelectionListener(e -> {
            boolean selected = tbl_videos.getSelectedRow() != -1;

            btn_likeVideo.setEnabled(selected);
            btn_dislikeVideo.setEnabled(selected);
        });

        lbl_welcome.setText("Bem-vindo(a), " + user.getName());
        

    }

    public User getUser() {
        return user;
    }
    
     public javax.swing.JTextField getTxtSearchVideo() {
        return txt_searchVideo;
    }

    public javax.swing.JButton getBtnSearchVideo() {
        return btn_searchVideo;
    }

    public javax.swing.JTable getTbl_videos() {
        return tbl_videos;
    }
    
    public javax.swing.JButton getBtn_favoriteVideo(){
        return btn_favoriteVideo;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Logout = new javax.swing.JButton();
        lbl_welcome = new javax.swing.JLabel();
        txt_searchVideo = new javax.swing.JTextField();
        btn_searchVideo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_videos = new javax.swing.JTable();
        btn_likeVideo = new javax.swing.JButton();
        btn_dislikeVideo = new javax.swing.JButton();
        btn_favoriteVideo = new javax.swing.JButton();
        btn_openFavorites = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Logout.setText("Sair");
        btn_Logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Logout.addActionListener(this::btn_LogoutActionPerformed);

        lbl_welcome.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        lbl_welcome.setText("                 BEM VINDO!");
        lbl_welcome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txt_searchVideo.addActionListener(this::txt_searchVideoActionPerformed);

        btn_searchVideo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_searchVideo.setText("Buscar");
        btn_searchVideo.addActionListener(this::btn_searchVideoActionPerformed);

        tbl_videos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Título", "Tipo", "Gênero", "Situação", "Likes", "Dislikes", "Favorito"
            }
        ));
        jScrollPane2.setViewportView(tbl_videos);

        btn_likeVideo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_likeVideo.setText("Curtir");
        btn_likeVideo.addActionListener(this::btn_likeVideoActionPerformed);

        btn_dislikeVideo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_dislikeVideo.setText("Descurtir");
        btn_dislikeVideo.addActionListener(this::btn_dislikeVideoActionPerformed);

        btn_favoriteVideo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_favoriteVideo.setText("Favoritar");
        btn_favoriteVideo.addActionListener(this::btn_favoriteVideoActionPerformed);

        btn_openFavorites.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_openFavorites.setText("Favoritos");
        btn_openFavorites.addActionListener(this::btn_openFavoritesActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txt_searchVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_searchVideo)
                .addGap(0, 113, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Logout)
                        .addGap(15, 15, 15))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btn_favoriteVideo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_likeVideo)
                .addGap(18, 18, 18)
                .addComponent(btn_dislikeVideo)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btn_openFavorites)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_welcome)
                    .addComponent(btn_Logout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btn_openFavorites)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_searchVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_searchVideo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_likeVideo)
                    .addComponent(btn_dislikeVideo)
                    .addComponent(btn_favoriteVideo))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogoutActionPerformed
        new view.Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_LogoutActionPerformed

    private void txt_searchVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchVideoActionPerformed
        btn_searchVideo.doClick();
    }//GEN-LAST:event_txt_searchVideoActionPerformed

    private void btn_searchVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchVideoActionPerformed
        c.searchVideo();
    }//GEN-LAST:event_btn_searchVideoActionPerformed

    private void btn_likeVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_likeVideoActionPerformed
        c.reactToSelectedVideo("LIKE");
    }//GEN-LAST:event_btn_likeVideoActionPerformed

    private void btn_dislikeVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dislikeVideoActionPerformed
        c.reactToSelectedVideo("DISLIKE");
    }//GEN-LAST:event_btn_dislikeVideoActionPerformed

    private void btn_favoriteVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_favoriteVideoActionPerformed
         c.toggleFavoriteSelectedVideo();
    }//GEN-LAST:event_btn_favoriteVideoActionPerformed

    private void btn_openFavoritesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openFavoritesActionPerformed
        new view.Favorites(user).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_openFavoritesActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Home().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Logout;
    private javax.swing.JButton btn_dislikeVideo;
    private javax.swing.JButton btn_favoriteVideo;
    private javax.swing.JButton btn_likeVideo;
    private javax.swing.JButton btn_openFavorites;
    private javax.swing.JButton btn_searchVideo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JTable tbl_videos;
    private javax.swing.JTextField txt_searchVideo;
    // End of variables declaration//GEN-END:variables
}
