/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.User;

/**
 *
 * @author Ricardo Ferreira
 */
public class Home extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Home.class.getName());
    private User user;

    /**
     * Creates new form Home
     */
    public Home(User user) {
        initComponents();
        this.user = user;
        
        lbl_welcome.setText("Bem-vindo(a), " + user.getName());

    }
     public javax.swing.JTextField getTxtSearchVideo() {
        return txt_searchVideo;
    }

    public javax.swing.JButton getBtnSearchVideo() {
        return btn_searchVideo;
    }

    public javax.swing.JTextArea getTxtAreaResults() {
        return txt_areaResults;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Logout = new javax.swing.JButton();
        lbl_welcome = new javax.swing.JLabel();
        txt_searchVideo = new javax.swing.JTextField();
        btn_searchVideo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_areaResults = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Logout.setText("Sair");
        btn_Logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Logout.addActionListener(this::btn_LogoutActionPerformed);

        lbl_welcome.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        lbl_welcome.setText("                                BEM VINDO!");
        lbl_welcome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txt_searchVideo.addActionListener(this::txt_searchVideoActionPerformed);

        btn_searchVideo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_searchVideo.setText("Buscar");
        btn_searchVideo.addActionListener(this::btn_searchVideoActionPerformed);

        txt_areaResults.setColumns(20);
        txt_areaResults.setRows(5);
        jScrollPane1.setViewportView(txt_areaResults);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_welcome, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Logout)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addComponent(txt_searchVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_searchVideo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lbl_welcome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btn_Logout)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_searchVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_searchVideo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogoutActionPerformed
        new view.Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_LogoutActionPerformed

    private void txt_searchVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchVideoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchVideoActionPerformed

    private void btn_searchVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchVideoActionPerformed
        txt_areaResults.setText("Buscando: " + txt_searchVideo.getText()); 
    }//GEN-LAST:event_btn_searchVideoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Home().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Logout;
    private javax.swing.JButton btn_searchVideo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JTextArea txt_areaResults;
    private javax.swing.JTextField txt_searchVideo;
    // End of variables declaration//GEN-END:variables
}
